# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20170712_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, to='pokemon.PokemonType'),
        ),
    ]
